services:
  - type: web
    name: saif-portfolio
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn portfolio_site.wsgi:application
    postDeployCommand: "python create_superuser.py"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_site.settings
      - key: PYTHON_VERSION
        value: 3.12.3
